### ISSUE TITLE
Related Entities in ICAT Format, not PaNOSC

### ISSUE THREAD

**Issue by MRichards99** [ral-facilities/datagateway-api#311] opened 2022-01-31 12:03 UTC
**Description**:
Upon sending a request with an include filter, the included entity is returned in the ICAT format. This means the field name is in the ICAT format, as is all the data inside that related field (e.g. `createId` exists only in ICAT) and the relationship is in the ICAT format (e.g. are the contents of the related field in a list or just a dict).

The following examples demonstrates this:
Request: `http://{{datagateway-api}}/search-api/datasets/0-8401-1070-7?filter={"include": [{"relation": "documents"}]}`

Response:
```json
{
    "investigation": {
        "summary": "Day purpose item create. Visit hope mean admit. The tonight adult cut foreign would situation fund.\nPurpose study usually gas think. Machine world doctor rise be college treat.",
        "visitId": "4",
        "id": 2,
        "startDate": "2000-06-04 00:00:00+00:00",
        "releaseDate": "2000-02-10 00:00:00+00:00",
        "modId": "user",
        "endDate": "2000-09-14 00:00:00+00:00",
        "createTime": "2004-08-23 02:41:19+00:00",
        "name": "INVESTIGATION 2",
        "title": "Show fly image herself yard challenge by. Past site her number. Not weight half far move. Leader everyone skin still.\nProve begin boy those always dream write inside.",
        "doi": "0-9729806-3-6",
        "modTime": "2016-11-16 19:42:34+00:00",
        "createId": "user"
    },
    "id": 2,
    "description": "Beat professional blue clear style have. Light final summer. Or hour color maybe word side much team.\nMessage weight official learn especially nature. Himself tax west.",
    "startDate": "2000-10-13 00:00:00+00:00",
    "location": "/subject/break.jpeg",
    "modId": "user",
    "complete": true,
    "endDate": "2000-02-10 00:00:00+00:00",
    "name": "DATASET 2",
    "modTime": "2006-08-24 01:28:06+00:00",
    "doi": "0-8401-1070-7",
    "createTime": "2013-04-01 10:56:52+00:00",
    "createId": "user"
}
```

Note that `investigation` should actually be `documents`. Note that the value of that field should be in a list, because there is a 1-many relationship between Dataset and Document. Also note the data inside `investigation` has just been copied from Python ICAT and is not in PaNOSC format. 

It might be easier to tackle this in two steps - sort out the related field name (i.e. get the example to be `documents`) and get the data into PaNOSC format, then get the cardinality (list/dict) correct as a second step.

**Acceptance criteria**:
- [ ] Related entities should return in PaNOSC format, not in ICAT format
- [ ] Unskip relevant tests in `test_search_endpoint.py` and `test_get_entity_by_pid.py`

**Comment by VKTB** [comment] 2022-01-31 15:07
My initial thought was this should not happen as data should only be returned in the format that is described in the `pydantic` model classes. From the response above, it is not just the included entity (`investigation`) that is returned in ICAT format but the entity that is being queried (`dataset`) too. For example, there isn't a `createId` field in the `Dataset` PaNOSC entity.

Upon a closer look at the changes pushed to the `feature/search-endpoints-#268` branch, I noticed that the problem is inside the `get_with_pid` helper method
https://github.com/ral-facilities/datagateway-api/blob/12bdde5bdd164a1f7e2c69329c90b084f1f3cb52/datagateway_api/src/search_api/helpers.py#L80-L117

On line 117, `icat_query_data` is returned instead of being passed to the `from_icat` methodof the relevant PaNOSC pydantic model which is why the response contains data in the ICAT format. What needs to be done here is what we are actually doing in the `get_search` method above it - get the ICAT relations for the non-related fields and then pass the data to the `from_icat` method.

Considering that the changes on the `feature/search-endpoints-#268` branch are not yet merged, I believe that this "fix" should be added to that branch rather than in a new one.

**Closed** 2022-02-07 13:17 UTC
Labels: bug, expands-search-api
